instance_id = "coinex_no_hedge_taker"
market_worker_id = "darkpool_sol"
legacy_core_id = 5
trading = true
taker_fee = 3e-4
maker_fee = -1e-4
redis_url = "redis://127.0.0.1/"
quote_intval = 500

[spread_ema_config]
period = "1M"
intval = 500

[delay_ema_config]
period = "1M"
intval = 500

[[ex_credential_configs]]
exchange = "COINEXV2"
ak = "D9BC2821F6DE4592927292A90A255DA3"
sk = "A02D1A4F4340285A5C64835C5038A3D847214313ABC015D6"
user_id = "darkpool_sol_coinex4"

[[ex_credential_configs]]
exchange = "BINANCE"
ak = "DL6apwao2aDww4m6Vi02j4qOfQ1BcrofjGHQq8qAT4Fllkf5KZjUvnaQA6km8Y35"
sk = "I2MgwwjJo1vqT5L2sVLspd91ocyvZATyGUBpEzqcSAdrYmND6VW9aEoHR206uY5T"
user_id = "darkpool_sol_binance4"

[[strategy_config.offset_configs]]
period = "5M"
intval = 500
[[strategy_config.offset_configs]]
period = "30M"
intval = 1000
[[strategy_config.offset_configs]]
period = "8H"
intval = 3000
[[strategy_config.offset_configs]]
period = "1D"
intval = 3000

[strategy_config]
lead_max_delay = 100
lag_max_delay = 500
lead_max_expiration = 300
report_measurement = "coinex_no_hedge_taker"
order_report_measurement = "coinex_no_hedge_taker_order"


[[strategy_config.trade_assets]]
asset = "COINEXV2_SWAP_BTC-USDT"
lead_asset = "BINANCE_SWAP_BTC-USDT"
trading = true
pos_limit = 10
pos_unit_usd = 200
use_offset_period = "8H"
taker_threshold = 0
bias_rate = 3e-5


[[strategy_config.trade_assets]]
asset = "COINEXV2_SWAP_ETH-USDT"
lead_asset = "BINANCE_SWAP_ETH-USDT"
trading = true
pos_limit = 10
pos_unit_usd = 200
use_offset_period = "8H"
taker_threshold = 0
bias_rate = 3e-5


[[strategy_config.trade_assets]]
asset = "COINEXV2_SWAP_XRP-USDT"
lead_asset = "BINANCE_SWAP_XRP-USDT"
trading = true
pos_limit = 10
pos_unit_usd = 100
use_offset_period = "8H"
taker_threshold = 0
bias_rate = 3e-5


[[strategy_config.trade_assets]]
asset = "COINEXV2_SWAP_SOL-USDT"
lead_asset = "BINANCE_SWAP_SOL-USDT"
trading = true
pos_limit = 10
pos_unit_usd = 100
use_offset_period = "8H"
taker_threshold = 0
bias_rate = 3e-5


[[strategy_config.trade_assets]]
asset = "COINEXV2_SWAP_DOGE-USDT"
lead_asset = "BINANCE_SWAP_DOGE-USDT"
trading = true
pos_limit = 10
pos_unit_usd = 100
use_offset_period = "8H"
taker_threshold = 0
bias_rate = 3e-5


[[strategy_config.trade_assets]]
asset = "COINEXV2_SWAP_WIF-USDT"
lead_asset = "BINANCE_SWAP_WIF-USDT"
trading = true
pos_limit = 10
pos_unit_usd = 100
use_offset_period = "8H"
taker_threshold = 0
bias_rate = 3e-5


[[strategy_config.trade_assets]]
asset = "COINEXV2_SWAP_SUI-USDT"
lead_asset = "BINANCE_SWAP_SUI-USDT"
trading = true
pos_limit = 10
pos_unit_usd = 100
use_offset_period = "8H"
taker_threshold = 0
bias_rate = 3e-5